version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: examen_lenguaje
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  #pgbackups:
  #  container_name: Backup
  #  image: prodrigestivill/postgres-backup-local
  #  restart: always
  #  volumes:
  #    - ./backup:/backups
  #  links:
  #    - db:db
  #  depends_on:
  #    - db
  #  environment:
  #    - POSTGRES_HOST=db
  #    - POSTGRES_DB=ev_le_videos
  #    - POSTGRES_USER=postgres
  #    - POSTGRES_PASSWORD=admin
  #    - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
  #    - SCHEDULE=@every 0h05m00s
  #    - BACKUP_KEEP_DAYS=7
  #    - BACKUP_KEEP_WEEKS=4
  #    - BACKUP_KEEP_MONTHS=6
  #    - HEALTHCHECK_PORT=81